# Generated by Django 5.1.1 on 2024-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOCUMENTO', models.CharField(max_length=100, unique=True)),
                ('TIPO_DOCUMENTO', models.CharField(choices=[('MANUAL DE PROCESOS', 'Manual de procesos'), ('PROCEDIMIENTO', 'Procedimiento'), ('FORMULARIO', 'Formularios')], max_length=30)),
                ('DESCRIPCION', models.TextField(blank=True, null=True)),
                ('INICIO_VIGENCIA', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Base de documento',
                'verbose_name_plural': 'Base de documentos',
            },
        ),
    ]
