# Generated by Django 5.1.1 on 2024-09-28 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreDocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocs',
            name='VERSION',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
