# Generated by Django 5.1.1 on 2024-09-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreDocs', '0002_basedocs_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocs',
            name='INICIO_VIGENCIA',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
