# Generated by Django 5.1.1 on 2024-10-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreDocs', '0003_alter_basedocs_inicio_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocs',
            name='TIPO_DOCUMENTO',
            field=models.CharField(choices=[('01. MANUAL DE PROCESOS', 'Manual de procesos'), ('02. PROCEDIMIENTO', 'Procedimiento'), ('03. FORMULARIO', 'Formularios')], max_length=30),
        ),
    ]
